name: Main Build and Deploy Docs

on:
  push:
    branches:
      - main
    paths:
    # run if any file in the docs folder is pushed
      - 'doc/**'    
      - '.github/workflows/docs.yml'    
  workflow_run:
    branches:
      - main
    workflows: ["Main Test and Release"]
    types:
      - completed
env:
  CACHE_NAME: api-reference

jobs:
  # check if api_reference is cached
  check_cache:
    runs-on: ubuntu-latest
    outputs:
      cache-exists: ${{ steps.cache-apo-reference.outputs.cache-hit }}
    steps:
      - name: Cache Api reference
        id: cache-apo-reference
        uses: actions/cache@v3
        with:
          path: doc/docs/reference
          key: ${{ env.CACHE_NAME }}

  build_api_reference:
    # run after check cache
    needs: check_cache
    # Run if Code files are updated (and test complete)
    # OR if cache doesn't exist
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || needs.check_cache.outputs.cache-exists == 'false' }}

    runs-on: ubuntu-latest
    # available list of containers here:
    # https://hub.docker.com/r/unityci/editor/tags?page=1&ordering=last_updated&name=ubuntu-2020.1.17f1-base
    container: unityci/editor:ubuntu-2021.3.4f1-base-1.0.1

    steps:
      - name: Activate unity
        # exit code is 1 for manual activation
        continue-on-error: true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2021_3_4 }}
        run: |          
          echo "$UNITY_LICENSE" | tr -d '\r' > UnityLicenseFile.ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile UnityLicenseFile.ulf -quit


      - uses: actions/checkout@v1

      - name: Cache Library
        id: cache-library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Library-2021.3.4

      - name: Generate Solution
        run: unity-editor -nographics -logFile /dev/stdout -customBuildName Mirage -projectPath . -executeMethod GitTools.Solution.Sync -quit

      # unity 2020.3 outputs <ReferenceOutputAssembly>false</ReferenceOutputAssembly> on linux
      # this breaks references to other csproj for docfx and sonar.
      # This step is a work around for this so docfx runs in correctly
      # replacing false with true in ReferenceOutputAssembly
      - name: Fix Csproj
        run: sed -i 's/<ReferenceOutputAssembly>false<\/ReferenceOutputAssembly>/<ReferenceOutputAssembly>true<\/ReferenceOutputAssembly>/g' *.csproj

      - uses: nikeee/docfx-action@v1.0.0
        with:
          args: metadata --logLevel Warning doc/docfx.json

      # Pull the api cache
      - name: Cache Api reference
        id: cache-apo-reference
        uses: actions/cache@v3
        with:
          path: doc/docs/reference
          key: ${{ env.CACHE_NAME }}
      
      # Clear old api
      - name: Clear Api reference directory
        run: rm -rf doc/docs/reference/*
      
      # Build new api (will update cache when job finishes)
      - name: Convert metadata to markdown
        uses: fillefilip8/DocFxToMarkdown@1.4.0
        with:
          input-folder: doc/api
          output-folder: doc/docs/reference

  build_and_deploy:
    # always run, but wait for build_api_reference first
    # we only run build_api_reference if code has changed, or if no api found
    if: ${{ always() }}
    needs: build_api_reference
    
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v1

      # pull cache
      - name: Cache Api reference
        id: cache-api-reference
        uses: actions/cache@v3
        with:
          path: doc/docs/reference
          key: ${{ env.CACHE_NAME }}

      # copies change log from mirage folder to docs
      - name: Copy Change Log
        run: cp "Assets/Mirage/CHANGELOG.md" "doc/docs/general/"

      - name: Install dependencies
        working-directory: doc
        run: npm ci

      - name: Download EmbedCodeInMarkdown
        run: curl -LJO https://github.com/James-Frowen/EmbedCodeInMarkdown/releases/download/v1.0.1/EmbedCodeInMarkdown
      
      - name: Run EmbedCodeInMarkdown
        run: chmod +x ./EmbedCodeInMarkdown && ./EmbedCodeInMarkdown -docs="doc/docs/" -code="Assets/Mirage/Samples~/"

      - name: Build docusaurus
        working-directory: doc
        run: npm run build
        env:
          ORG_NAME: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Publish docs
        uses: crazy-max/ghaction-github-pages@v3.1.0
        if: github.ref == 'refs/heads/main'
        with:
          # Create incremental commit instead of doing push force
          keep_history: true
          # Allow an empty commit to be created
          allow_empty_commit: true
          jekyll: false
          # Build directory to deploy
          build_dir: doc/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
