name: CI
#on:
#  pull_request: {}
#  push: { branches: [master] }

on: 
  workflow_dispatch

jobs:
  Tests2022:
    name: Test 2022
    runs-on: ubuntu-latest
    # available list of containers here:
    # https://hub.docker.com/r/unityci/editor/tags?page=1&ordering=last_updated&name=ubuntu-2020.1.17f1-base
    container: unityci/editor:ubuntu-2022.2.0f1-base-1.0.1

    steps:
      - name: Activate unity
        # exit code is 1 for manual activation
        continue-on-error: true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2022_2_0 }}
        run: |          
          echo "$UNITY_LICENSE" | tr -d '\r' > UnityLicenseFile.ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile UnityLicenseFile.ulf -quit 
      
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Cache Library
        id: cache-library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-2022.2.0

      - name: Run editor Tests
        run: unity-editor -nographics -logFile /dev/stdout -runTests -testPlatform editmode -testResults Tests/editmode-results.xml -enableCodeCoverage -coverageResultsPath Tests -debugCodeOptimization 
        timeout-minutes: 20
        
      - name: Run play Tests
        run: unity-editor -nographics -logFile /dev/stdout -runTests -testPlatform playmode -testResults Tests/playmode-results.xml -enableCodeCoverage -coverageResultsPath Tests -debugCodeOptimization 
        timeout-minutes: 20

      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results 2022
          path: Tests

      - name: Publish test results
        uses: MirageNet/nunit-reporter@v1.0.11
        if: always()
        with:
          reportTitle: Test Report 2022
          path: "Tests/*.xml"
          access-token: ${{ secrets.GITHUB_TOKEN }}
  